package mgstation;
// Generated 1 mars 2017 15:29:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name="produit"
    ,schema="public"
)
public class Produit  implements java.io.Serializable {


     private int idproduit;
     private Unite unite;
     private String designation;
     private Set<Stock> stocks = new HashSet<Stock>(0);
     private Set<Prix> prixes = new HashSet<Prix>(0);

    public Produit() {
    }

	
    public Produit(int idproduit, Unite unite) {
        this.idproduit = idproduit;
        this.unite = unite;
    }
    public Produit(int idproduit, Unite unite, String designation, Set<Stock> stocks, Set<Prix> prixes) {
       this.idproduit = idproduit;
       this.unite = unite;
       this.designation = designation;
       this.stocks = stocks;
       this.prixes = prixes;
    }
   
     @Id 

    
    @Column(name="idproduit", unique=true, nullable=false)
    public int getIdproduit() {
        return this.idproduit;
    }
    
    public void setIdproduit(int idproduit) {
        this.idproduit = idproduit;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idunite", nullable=false)
    public Unite getUnite() {
        return this.unite;
    }
    
    public void setUnite(Unite unite) {
        this.unite = unite;
    }

    
    @Column(name="designation", length=200)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produit")
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produit")
    public Set<Prix> getPrixes() {
        return this.prixes;
    }
    
    public void setPrixes(Set<Prix> prixes) {
        this.prixes = prixes;
    }




}


