package mgstation;
// Generated 1 mars 2017 15:29:17 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name="stock"
    ,schema="public"
)
public class Stock  implements java.io.Serializable {


     private int idstock;
     private Produit produit;
     private Integer entre;
     private Integer sortie;
     private Date date;

    public Stock() {
    }

	
    public Stock(int idstock, Produit produit) {
        this.idstock = idstock;
        this.produit = produit;
    }
    public Stock(int idstock, Produit produit, Integer entre, Integer sortie, Date date) {
       this.idstock = idstock;
       this.produit = produit;
       this.entre = entre;
       this.sortie = sortie;
       this.date = date;
    }
   
     @Id 

    
    @Column(name="idstock", unique=true, nullable=false)
    public int getIdstock() {
        return this.idstock;
    }
    
    public void setIdstock(int idstock) {
        this.idstock = idstock;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idproduit", nullable=false)
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }

    
    @Column(name="entre")
    public Integer getEntre() {
        return this.entre;
    }
    
    public void setEntre(Integer entre) {
        this.entre = entre;
    }

    
    @Column(name="sortie")
    public Integer getSortie() {
        return this.sortie;
    }
    
    public void setSortie(Integer sortie) {
        this.sortie = sortie;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=13)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


