package mgstation;
// Generated 1 mars 2017 15:29:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unite generated by hbm2java
 */
@Entity
@Table(name="unite"
    ,schema="public"
)
public class Unite  implements java.io.Serializable {


     private int idunite;
     private String unite;
     private Set<Produit> produits = new HashSet<Produit>(0);

    public Unite() {
    }

	
    public Unite(int idunite) {
        this.idunite = idunite;
    }
    public Unite(int idunite, String unite, Set<Produit> produits) {
       this.idunite = idunite;
       this.unite = unite;
       this.produits = produits;
    }
   
     @Id 

    
    @Column(name="idunite", unique=true, nullable=false)
    public int getIdunite() {
        return this.idunite;
    }
    
    public void setIdunite(int idunite) {
        this.idunite = idunite;
    }

    
    @Column(name="unite", length=3)
    public String getUnite() {
        return this.unite;
    }
    
    public void setUnite(String unite) {
        this.unite = unite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unite")
    public Set<Produit> getProduits() {
        return this.produits;
    }
    
    public void setProduits(Set<Produit> produits) {
        this.produits = produits;
    }




}


