package mgstation;
// Generated 1 mars 2017 15:29:17 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name="utilisateur"
    ,schema="public"
)
public class Utilisateur  implements java.io.Serializable {


     private int idutilisateur;
     private String utilisateur;
     private String pass;

    public Utilisateur() {
    }

	
    public Utilisateur(int idutilisateur) {
        this.idutilisateur = idutilisateur;
    }
    public Utilisateur(int idutilisateur, String utilisateur, String pass) {
       this.idutilisateur = idutilisateur;
       this.utilisateur = utilisateur;
       this.pass = pass;
    }
   
     @Id 

    
    @Column(name="idutilisateur", unique=true, nullable=false)
    public int getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(int idutilisateur) {
        this.idutilisateur = idutilisateur;
    }

    
    @Column(name="utilisateur", length=200)
    public String getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(String utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="pass", length=200)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


